#图片配置文件，用于指定所有图片的映射关系
#格式：XXX=图片全路径
#键值请注意不要重复
#窗口
beginBackground=src/main/resources/img/bg/title.png
gameOver=src/main/resources/img/bg/gameover.png
rect1=src/main/resources/img/bg/rect1.png
rect2=src/main/resources/img/bg/rect2.png
rect3=src/main/resources/img/bg/rect3.png
rect4=src/main/resources/img/bg/rect4.png
#玩家
PlayerA=src/main/resources/img/player/player1.png
PlayerB=src/main/resources/img/player/player2.png
#Map 地图路径
mapFloor=src/main/resources/img/map/1.png
mapObstacle=src/main/resources/img/map/2.png
floor=src/main/resources/img/map/floor.png
#道具路径
magicBox1=src/main/resources/img/item/1.png
magicBox2=src/main/resources/img/item/2.png
magicBox3=src/main/resources/img/item/3.png
magicBox4=src/main/resources/img/item/4.png
magicBox5=src/main/resources/img/item/5.png
magicBox6=src/main/resources/img/item/6.png
magicBox7=src/main/resources/img/item/7.png
magicBox8=src/main/resources/img/item/8.png
magicBox9=src/main/resources/img/item/9.png
#Bubble水泡路径
Bubble=src/main/resources/img/boom/1.png
#水泡爆炸图片路径
explodeUp=src/main/resources/img/boom/up.png
explodeDown=src/main/resources/img/boom/down.png
explodeLeft=src/main/resources/img/boom/left.png
explodeRight=src/main/resources/img/boom/right.png
explodeCenter=src/main/resources/img/boom/center.png
#npcA图片路径
npcA0=src/main/resources/img/computer/1/down.png
npcA1=src/main/resources/img/computer/1/left.png
npcA2=src/main/resources/img/computer/1/right.png
npcA3=src/main/resources/img/computer/1/up.png
#npcB图片路径
npcB0=src/main/resources/img/computer/2/down.png
npcB1=src/main/resources/img/computer/2/left.png
npcB2=src/main/resources/img/computer/2/right.png
npcB3=src/main/resources/img/computer/2/up.png
#npcC图片路径
npcC0=src/main/resources/img/computer/3/down.png
npcC1=src/main/resources/img/computer/3/left.png
npcC2=src/main/resources/img/computer/3/right.png
npcC3=src/main/resources/img/computer/3/up.png